<h1> This is by https://www.mohammadmonjureelahi.com</h1>

<p>I have years of experience in the technology industry. Immediately after graduating from <a href="https://www.buet.ac.bd/web/">Banagladesh University of Engineering and Technology(BUET),</a>  the premier engineering university of my home country Bangladesh, I had the opportunity to join the leading telecom company <a href="https://www.grameenphone.com/about/discover-gp/about-grameenphone">Grameenphone Ltd.</a> which is predominantly owned by <a href="https://www.telenor.com/">Telenor group</a>. I worked for the technical division where I worked with the configuration of various telecom equipment and took part in building the largest telecom network in the country. Later I had the opprotunity to work with the IT wing of my department. I had worked as a freelance system and network administrator before I migrated to Canada. </p>
            <p>Currently I have been nearing completion of my schooling on IT Professional diploma along with writing relevant vendor certifications to validate and further strengthen my skill and knowledge in IT so that I can have my dream career in Information Technology.</p>
            <p>Currently I have been nearing completion of my schooling on IT Professional diploma along with writing relevant vendor certifications to validate and further strengthen my skill and knowledge in IT so that I can have my dream career in Information Technology.</p>
            <p>Currently I have been nearing completion of my schooling on IT Professional diploma along with writing relevant vendor certifications to validate and further strengthen my skill and knowledge in IT so that I can have my dream career in Information Technology.</p>
            
<h2> Learn QA Automation tools + Devops Tools CI/CD pipelines in from Scratch</h2>
<h2> Good Luck and we are almost done with the course.Thankyou</h2>
